spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://prod-db:3306/water_melt?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    druid:
      # 生产环境连接池配置
      initial-size: 10
      min-idle: 10
      max-active: 50
      # 启用加密
      connection-properties: config.decrypt=true;config.decrypt.key=${DRUID_DECRYPT_KEY}
      filter:
        config:
          enabled: true

  # Redis配置
  data:
    redis:
      host: prod-redis
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

# 日志配置
logging:
  level:
    root: warn
    com.watermelt: info
  file:
    name: /var/log/water-melt/water-melt-prod.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 3GB
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# MyBatis Plus配置
mybatis-plus:
  configuration:
    # 生产环境关闭SQL日志
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# Knife4j配置
knife4j:
  # 生产环境关闭接口文档
  enable: false
  basic:
    enable: true
    username: ${KNIFE4J_USERNAME}
    password: ${KNIFE4J_PASSWORD}

# 系统配置
system:
  # 文件上传路径
  upload-path: /data/water-melt/upload/
  # 生产环境跨域配置
  cors:
    allowed-origins:
      - https://water-melt.com
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "Authorization,Content-Type,X-Requested-With"
    allow-credentials: true
    max-age: 3600

# 安全配置
security:
  # 启用HTTPS
  require-ssl: true
  headers:
    hsts: true
    frame-options: DENY
    xss-protection: 1; mode=block
    content-security-policy: "default-src 'self'" 