spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/water_melt?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password:

# 服务器配置
server:
  port: 8082
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    root: info
    com.watermelt: debug
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.data: debug
  file:
    name: logs/water-melt-dev.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# MyBatis Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Knife4j配置
knife4j:
  enable: true
  basic:
    enable: false

# 应用配置
app:
  upload:
    dir: D:/water-melt/upload/

# 系统配置
system:
  # 开发环境跨域配置
  cors:
    allowed-origins:
      - http://localhost:8080
      - http://localhost:3000
      - http://localhost:8081
      - http://localhost:8082
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600 